markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
domain: crazynew.github.com
title: Crazynew's Blog
description:Java Web, Linux, Design Patterns,reading...
author: Victor Zhou
email: huixingworld#163.com
github: Crazynew

config:
  js_dir:
  img_dir:
  css_dir:
